export declare enum ApiError {
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
  EMAIL_IN_USE = 'EMAIL_IN_USE',
  MISSING_PARAMETERS = 'MISSING_PARAMETERS',
  MISSING_USER_INFO = 'MISSING_USER_INFO',
  MISSING_EMAIL = 'MISSING_EMAIL',
  ERROR_CREATING_ACCOUNT = 'ERROR_CREATING_ACCOUNT',
}
